jquery_lang_js.prototype.lang.hu = {
	'text':'teks',
	'Open File':'Buka Fail',
	'Find Place':'Jejak Lokasi',
	'New Map':'Peta Baru',
	'Default location':'Lokasi lalai',
	'Export':'Eksport',
	'Import':'Import',
	'Options':'Opsyen',
	'Add Point':'Tambah titik',
	'Maps':'Térképek',
	'Draw':'rajzol',
	'Build Route':'Bina laluan',
	'Help':'Segítség',
	'Manual':'Panduan',
	'GB Maps':'GB Maps',
	'Language':'Bahasa',
	'Invert Line':'Terbalikan Garis',
	'Clear All':'Hapus Semua',
	'Troubleshooting':'Penyelesai Masalah',
	'System Requirements':'Rendszerkövetelmények',
	'Credits':'Credits',
	'Abouts':'abouts',
	'Build':'épít',
	'Objects List':'objektumok listája',
	'Lines List':'Lines lista',
	'BVE Rail Type':'BVE Rail Type',
	'Theme Selection':'téma kiválasztása',
}