jquery_lang_js.prototype.lang.jp = {
	'text':'ギビマップ',
	'Open File':'オープンファイル',
	'Find Place':'場所を見つける',
	'New Map':'新規マップ',
	'Default location':'デフォルトの場所',
	'Export':'エクスポート',
	'Import':'インポート',
	'Options':'オプション',
	'Add Point':'ポイントの追加',
	'Map':'地図',
	'Draw':'描く',
	'Build Route':'ルートを構築する',
	'Help':'アシスト',
	'Manual':'マニュアル',
	'GB Maps':'ギビマップ',
	'Language':'言語',
	'Invert Line':'ラインを反転',
	'Clear All':'すべてクリア',
	'Troubleshooting':'不良診断',
	'System Requirements':'システム要件',
	'Credits':'鑑賞',
	'Abouts':'約',
	'Build':'作る',
	'Objects List':'オブジェクト一覧',
	'Lines List':'ライン一覧',
	'BVE Rail Type':'BVEレールタイプ',
	'Theme Selection':'テーマ選択',		
}