jquery_lang_js.prototype.lang.my = {
	'text':'teks',
	'Open File':'Buka Fail',
	'Find location':'Cari Lokasi',
	'New Map':'Peta Baru',
	'Default location':'Lokasi lalai',
	'Export':'Eksport',
	'Import':'Import',
	'Options':'Opsyen',
	'Add Point':'Tambah titik',
	'Maps':'Peta',
	'Draw':'Lukis',
	'Build Route...':'Bina laluan',
	'Help':'Bantu',
	'Manual':'Panduan',
	'GB Maps':'GB Maps',
	'Language':'Bahasa',
	'Invert Line':'Terbalikan Garis',
	'Clear All':'Hapus Semua',
	'Troubleshooting':'Penyelesai Masalah',
	'System Requirements':'Keperluan Sistem',
	'Credits':'Penghargaan',
	'Abouts':'Perihal',
	'Build':'Bina',
	'Objects List':'Senarai objek',
	'Lines List':'Senarai Garis',
	'BVE Rail Type':'Jenis Rail BVE',
	'Theme Selection':'Pemilih Tema',	
	'File name : ':'Nama fail : ',
	'Save file (via JavaScript) is unsupported, due to browser limitation, security issue and also browser incompatibility. Please copy this texts and save file manually with your text editor (e.g : Notepad). Select &lt;Ctrl+A&gt; and copy &lt;Ctrl+C&gt; the following text to your text editor.':'Simpan fail (melalui JavaScript) tidak tersokong, disebabkan oleh batasan pelayar, isu keselamatan dan juga ketidakserasian pelayar. Sila salin teks ini dan simpan fail secara manual dengan penyunting teks anda (cth: Notepad). Pilih &lt;Ctrl+A&gt; dan Salin &lt;Ctrl+C&gt; teks berikut ke editor teks anda.',
	'Export Data...':'Mengeksport Data...',
	'Import Data...':'Import Data...',
	'Paste &lt;Ctrl+V&gt; GB Maps ギビマップ data in the following text box.':'Tampal &lt;Ctrl+V&gt; data GB Maps ギビマップ ke dalam kotak teks yang berikut.',
	'Import ...':'Import ...',
	'Find ...':'Mencari...',
	'Find location (e.g : "Kanita, Japan" OR "Rawang"): ':'Mencari lokasi (cth: "Kanita, Jepun" atau "Rawang"):',
	'System Requirement':'Keperluan sistem',
	'Common browser that support Google Maps, Javascript, CSS, local file cookie and HTML5. This application is semi online, so your computer must have an internet connection and no firewall restriction to Google Maps or any Google services.':'Pelayar biasa yang menyokong Google Maps, Javascript, CSS, cookie fail tempatan dan HTML5. Aplikasi ini adalah separa online, komputer anda mesti mempunyai sambungan internet dan tiada sekatan firewall ke atas Google Maps atau mana-mana servis Google.',
	'Click to stop line or shape editing, OR to move the map.':'Klik untuk menghentikan suntingan garis atau bentuk, atau untuk menggerakkan peta.',
	'Draw a line (polyline).&#xA;Click on this button and click anywhere on the map.&#xA;Click on the "hand" icon to stop drawing.&#xA;Right click on markers (dots) to delete it.':'Lukis satu garisan (polyline). &#xA; Klik pada butang ini dan klik di manapun pada peta. &#xA; Klik ikon "tangan" untuk berhenti melukis. &#xA; Klik kanan pada penanda (titik) untuk memadamnya.',
	'Draw a polygon.&#xA;Click this button and click anywhere on the map.&#xA;Click on the "hand" icon to stop drawing.&#xA;Right click on markers (dots) to delete it.&#xA;Currently, this feature is just a drawing.&#xA;Unused in BVE code generator.':'Lukiskan poligon. &#xA; Klik butang ini dan klik di mana-mana pada peta. &#xA;Klik ikon "tangan" untuk berhenti melukis. &#xA;Klik kanan pada penanda (titik) untuk memadam ia.&#xA;Pada masa ini, fitur ini sekadar lukisan.&#xA;Tidak digunakan oleh penjana kod BVE.',
	'Draw a circle.&#xA;Click this button and click anywhere on the map.&#xA;Currently, this feature is just a drawing.&#xA;Unused in BVE code generator.':'Lukis bulatan.&#xA;klik butang ini dan klik di manapun pada peta.&#xA;Pada masa ini, fitur ini sekadar lukisan.&#xA;Tidak digunakan oleh penjana kod BVE.',
	'Draw a rectangle with two point.&#xA;Click this button and click on two corners of the squares on a map.&#xA;Currently, this feature is just a drawing.&#xA;Unused in BVE code generator.':'Lukis segi empat dengan dua titik.&#xA;Klik butang ini dan klik pada dua penjuru segi empat di atas peta.&#xA;Pada masa ini, fitur ini sekadar lukisan.&#xA;Tidak digunakan oleh penjana kod BVE.',
	'Draw a marker on the map.&#xA;Currently, this feature is just a drawing.&#xA;Unused in BVE code generator.':'Lukis penanda peta.&#xA;Pada masa ini, fitur ini sekadar lukisan.&#xA;Tidak digunakan oleh penjana kod BVE.',
	'Measure distance.':'Ukuran jarak.',
	'Measure angle.':'Ukuran sudut.',
	'Undo':'Undo',
	'Redo':'Redo',
	'Development platform':'Platform pembangunan',
	'Unsupported browser':'Pelayar tidak disokong',
	'Microsoft Internet Explorer 10 and below':'Microsoft Internet Explorer 10 dan ke bawah',
	'Google Chrome, unless local file cookie is enable. Please modify Google Chrome shortcut in Windows, "--enable-file-cookies". e.g. : ':'Google Chrome, melainkan cookie fail tempatan dibenarkan. Sila ubah suai pintasan Google Chrome dalam Windows, " --enable-file-cookies". cth. :',
	'Framework / plugins used:':'Framework/plugin yang digunakan:',
	'Development Info':'Info pembangunan',
	'Hardware requirements: as the minimum requirements for running Windows 7 smoothly.':'Keperluan hardware : seperti mana keperluan minimum bagi melarikan Windows 7 dengan lancar.',
	'1 gigahertz (GHz) or faster 32-bit (x86) or 64-bit (x64) processor':'1 gigahertz (GHz) atau lebih cepat 32-bit (x 86) atau pemproses 64-bit (x 64)',
	'1 gigabyte (GB) RAM (32-bit) or 2 GB RAM (64-bit)':'1 gigabit (GB) RAM (32-bit) atau 2 GB RAM (64-bit)',
	'16 GB available hard disk space (32-bit) or 20 GB (64-bit)':'16 GB ruang cakera keras (32-bit) atau 20 GB (64-bit)',
	'DirectX 9 graphics device with WDDM 1.0 or higher driver':'Peranti grafik DirectX 9 dengan WDDM 1.0 atau peranti yang lebih tinggi',
}